FROM python:3.8


COPY requirements.txt requirements.txt
COPY google_auth.json google_auth.json 

COPY gcp/merger/main.py main.py

RUN pip3 install --upgrade pip
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y tzdata \
    libgdal-dev

RUN pip install --upgrade pip
RUN pip install gdal==3.0.4

CMD ["python"]