FROM continuumio/miniconda3

WORKDIR /app
COPY environment.yml /app

# Create the environment:
RUN conda env create -f environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "landcover-mapping", "/bin/bash", "-c"]
ENV PATH /opt/conda/envs/env/bin:$PATH