.dvcignore
.gitignore

train.sh
Dockerfile.train
Dockerfile.train.dockerignore
Dockerfile.inference
Dockerfile.inference.dockerignore
inference.sh
mypy.ini
pyproject.toml
README.md

.dvc/
.mypy_cache/
data/
diagrams/
scripts/
src/
test/