name: landcover-mapping
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6  # earthengine doesn't work with python 3.7
  - dataclasses  # only introduced in python 3.7
  - earthengine-api
  - mypy
  - black
  - pandas
  - xarray
  - netcdf4
  - rasterio
  - jupyter
  - matplotlib
  - pip
  - cudatoolkit=10.2  # this is the only new thing in the GPU yml file
  - pyproj
  - tqdm
  - geopandas
  - cartopy
  - scikit-learn
  - dvc-s3
  - gdal
  - rclone
  - pip:
      - pytorch-lightning==0.7.1  # lots of API changes
      - torch==1.6.0
      - clearml
