"""
Combines the earth observation data with the labels to create (x, y) training data
"""
from pathlib import Path

import os
import pandas as pd
import sys

# Change the working directory to the directory of this script
os.chdir(os.path.dirname(os.path.realpath(__file__)))

sys.path.append("..")

from src.utils import data_dir  # noqa: E402
from src.ETL.dataset import load_all_features_as_df  # noqa: E402
from src.datasets_labeled import labeled_datasets  # noqa: E402


def check_empty_features(features_df: pd.DataFrame, remove: bool = False) -> str:
    """
    Some exported tif data may have nan values
    """
    empties = features_df[features_df["labelled_array"].isnull()]
    num_empty = len(empties)
    if num_empty > 0:
        if remove:
            empties.filename.apply(lambda p: Path(p).unlink())
        return f"\u2716 Found {num_empty} empty features"
    else:
        return "\u2714 Found no empty features"


def check_duplicates(features_df: pd.DataFrame, remove: bool = False) -> str:
    """
    Can happen when not all tifs have been downloaded and different labels are matched to same tif
    """
    cols_to_check = ["instance_lon", "instance_lat", "source_file"]
    duplicates = features_df[features_df.duplicated(subset=cols_to_check)]
    num_dupes = len(duplicates)
    if num_dupes > 0:
        if remove:
            duplicates.filename.apply(lambda p: Path(p).unlink())
        return f"\u2716 Found {num_dupes} duplicates"
    else:
        return "\u2714 No duplicates found"


if __name__ == "__main__":
    report = "DATASET REPORT (autogenerated, do not edit directly)"
    for d in labeled_datasets:
        if d.dataset != "one_acre_fund":
            text = d.create_features()
            report += "\n\n" + text

    features_df = load_all_features_as_df()
    empty_text = check_empty_features(features_df)
    print(empty_text)
    duplicates_text = check_duplicates(features_df)
    print(duplicates_text)
    report += "\n\nAll data:\n" + empty_text + "\n" + duplicates_text

    with (data_dir / "datasets.txt").open("w") as f:
        f.write(report)
