name: Build 

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted
    env:
      CONDA_ENV: /gpfs/data1/cmongp1/izvonkov/envs/landcover-mapping/bin
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2        
    - name: Run type checks
      run: |
        $CONDA_ENV/mypy src scripts
    - name: Run flake8
      run: |
        $CONDA_ENV/flake8 src data scripts test gcp
    - name: Run unit tests
      run: |
        $CONDA_ENV/python -m unittest
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true              
    - name: Get data for integration test
      run: |
        $CONDA_ENV/dvc pull data/features
        $CONDA_ENV/dvc pull data/processed
        $CONDA_ENV/dvc pull data/models
#     - name: Run integration test
#       run: |
#         $CONDA_ENV/python -m unittest test/integration_test_labeled.py
      


