name: Build 

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: activate conda environment
      run: |
        conda --version
        conda env list
        conda activate landcover-mapping
        
    - name: Run type checks
      run: |
        which mypy
        mypy src scripts
    - name: Run flake8
      run: |
        which flake8
        flake8 src data scripts test gcp
    - name: Run unit tests
      run: |
        pip install coverage
        coverage run -m unittest
        coverage xml
#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v1
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         files: coverage.xml
#         fail_ci_if_error: true
#         verbose: true
    # - name: Set up Cloud SDK
    #   uses: google-github-actions/setup-gcloud@master
    #   with:
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
              
    # - name: Get data for integration test
    #   if: github.ref == 'refs/heads/master'
    #   run: |
    #     dvc pull data/features
    #     dvc pull data/models
    # - name: Run integration test
    #   if: github.ref == 'refs/heads/master'
    #   run: |
    #     cd test
    #     python -m unittest integration_test_predict.py
      


